### ISSUE TITLE
upload-rl uses cached version of Sequoia

### ISSUE THREAD

**Issue by lebrice** [fgolemo/cl-workshop-cvpr21-docker#11]
Both `make upload-sl` and `make upload-rl` use the cached layer for installing Sequoia, which might be older and cause submissions to fail, while the submission would work fine locally.

**Comment by fgolemo** [comment]
solved in https://github.com/fgolemo/cl-workshop-cvpr21-docker/commit/60633846f9febb9e75f6f25971cfd865c4aaf732
