### ISSUE TITLE
Unable to open file

### ISSUE THREAD

**Issue by LilioISnotAfox** [fgolemo/cl-workshop-cvpr21-docker#15]
Hello, today here is a new bug for me: when downloading data synbols then loading hdf5, it returns an error like this.
![image](https://user-images.githubusercontent.com/37403574/114825163-724c8600-9df8-11eb-8782-4330c77d26ff.png)
This did not happen before, please help me !

**Comment by qihao-huang** [comment]
exactly same for me! @fgolemo

**Comment by qihao-huang** [comment]
I tried to fetch the original git large file "https://github.com/ElementAI/synbols-resources/blob/master/datasets/generated/default_n%3D100000_2020-Oct-19.h5py", then I found the problem:
```bash
$ git lfs clone https://github.com/ElementAI/synbols-resources.git
WARNING: 'git lfs clone' is deprecated and will not be updated
          with new flags from 'git clone'

'git clone' has been updated in upstream Git to have comparable
speeds to 'git lfs clone'.
Cloning into 'synbols-resources'...
remote: Enumerating objects: 10052, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 10052 (delta 4), reused 19 (delta 3), pack-reused 10024
Receiving objects: 100% (10052/10052), 293.88 MiB | 1.54 MiB/s, done.
Resolving deltas: 100% (1834/1834), done.
Updating files: 100% (9124/9124), done.
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/ElementAI/synbols-resources.git/info/lfs'
```
@fgolemo Could you please help us solve this problem by purchasing more data packs to restore access.

**Comment by aldro61** [comment]
We are currently working on solving this. You can track progress here: https://github.com/ElementAI/synbols-resources/issues/5

**Comment by aldro61** [comment]
Issue https://github.com/ElementAI/synbols-resources/issues/5 is resolved, so you should be able to download the data via:

1. The downloader referenced in the synbols-benchmark code: https://github.com/ElementAI/synbols-benchmarks/blob/master/tools/download_dataset.py
2. Directly from Zenodo: https://zenodo.org/record/4701316

Git cloning the `synbols-resources` repo will not work.

Could you please confirm that it works?

**Comment by qihao-huang** [comment]
This issuse has been fixed. We can download this dataset. Thanks! @aldro61
