### ISSUE TITLE
OS Error (RL Track)

### ISSUE THREAD

**Issue by kevaldoshi17** [fgolemo/cl-workshop-cvpr21-docker#16]
Hi, I had submitted my code for the RL track and it returned an OS Error. Could you please help me out with the issue?

`=== RUNNING RL TRACK
Accessing missing attribute train_transforms from the 'remote' setting.
Accessing missing attribute steps_per_phase from the 'remote' setting.
Accessing missing attribute train_transforms from the 'remote' setting.
Accessing missing attribute val_transforms from the 'remote' setting.
1000
Reached the limit of 1000 steps.
Traceback (most recent call last):
  File \"./main.py\", line 69, in <module>
    run_rl_track(get_method_rl())
  File \"./main.py\", line 31, in run_rl_track
    return run_track(method, IncrementalRLSetting, \"rl_track.yaml\")
  File \"./main.py\", line 20, in run_track
    results = setting.apply(method)
  File \"/opt/conda/lib/python3.8/site-packages/sequoia/client/setting_proxy.py\", line 180, in apply
    results: Results = self.main_loop(method)
  File \"/opt/conda/lib/python3.8/site-packages/sequoia/client/setting_proxy.py\", line 355, in main_loop
    test_loop_results = self.test_loop(method)
  File \"/opt/conda/lib/python3.8/site-packages/sequoia/client/setting_proxy.py\", line 452, in test_loop
    obs = test_env.reset()
  File \"/opt/conda/lib/python3.8/site-packages/sequoia/client/env_proxy.py\", line 66, in reset
    obs = self.__environment.reset()
  File \"/opt/conda/lib/python3.8/site-packages/gym/wrappers/monitor.py\", line 38, in reset
    observation = self.env.reset(**kwargs)
  File \"/opt/conda/lib/python3.8/site-packages/gym/core.py\", line 237, in reset
    return self.env.reset(**kwargs)
  File \"/opt/conda/lib/python3.8/site-packages/sequoia/common/gym_wrappers/env_dataset.py\", line 301, in reset
    observation = self.env.reset(**kwargs)
  File \"/opt/conda/lib/python3.8/site-packages/sequoia/settings/active/continual/wrappers.py\", line 92, in reset
    observation = self.env.reset(**kwargs)
  File \"/opt/conda/lib/python3.8/site-packages/gym/core.py\", line 264, in reset
    observation = self.env.reset(**kwargs)
  File \"/opt/conda/lib/python3.8/site-packages/sequoia/common/gym_wrappers/multi_task_environment.py\", line 307, in reset
    observation = self.env.reset(**kwargs)
  File \"/opt/conda/lib/python3.8/site-packages/gym/core.py\", line 264, in reset
    observation = self.env.reset(**kwargs)
  File \"/opt/conda/lib/python3.8/site-packages/gym/core.py\", line 237, in reset
    return self.env.reset(**kwargs)
  File \"/opt/conda/lib/python3.8/site-packages/gym/wrappers/time_limit.py\", line 25, in reset
    return self.env.reset(**kwargs)
  File \"/opt/conda/lib/python3.8/site-packages/gym_ple/ple_env.py\", line 57, in reset
    self.ple_wrapper.reset_game()
  File \"/opt/conda/lib/python3.8/site-packages/ple/ple.py\", line 264, in reset_game
    self.game.reset()
  File \"/opt/conda/lib/python3.8/site-packages/ple/games/base/pygamewrapper.py\", line 180, in reset
    self.init()
  File \"/opt/conda/lib/python3.8/site-packages/meta_monsterkong/envs.py\", line 326, in init
    self.currentBoard = Board(
  File \"/opt/conda/lib/python3.8/site-packages/meta_monsterkong/board.py\", line 88, in __init__
    self.resetGroups()
  File \"/opt/conda/lib/python3.8/site-packages/meta_monsterkong/board.py\", line 107, in resetGroups
    pp = np.loadtxt(princessPath, dtype='int16')
  File \"/opt/conda/lib/python3.8/site-packages/numpy/lib/npyio.py\", line 961, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File \"/opt/conda/lib/python3.8/site-packages/numpy/lib/_datasource.py\", line 195, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File \"/opt/conda/lib/python3.8/site-packages/numpy/lib/_datasource.py\", line 535, in open
    raise IOError(\"%s not found.\" % path)
OSError: /opt/conda/lib/python3.8/site-packages/meta_monsterkong/maps/princess20.txt not found.`

**Comment by fgolemo** [comment]
@lebrice did you have a look at this by any chance?

**Comment by lebrice** [comment]
Im 99% sure this has already been fixed, @kevaldoshi17  did you update the competition repo with update.sh?

**Comment by kevaldoshi17** [comment]
I did and it installed most of the libraries but there is a dependency issue. 

`evalai 1.3.13 requires click==6.7, but you have click 8.0.1 which is incompatible.`

Manually tried installing click 6.7 but wandb requires click > 8.

**Comment by lebrice** [comment]
Sorry for the inconvenience!

(Edit: By the way, this `click` dependency issue isn't the problem, it's caused by not having the most up-to-date version of the `meta_monsterkong` package installed (`>=v0.0.1.post1`))

**Comment by kevaldoshi17** [comment]
Is there a fix that I can apply on my end because it is still not working?

**Comment by lebrice** [comment]
@kevaldoshi17  Running `update.sh` fixed your problem, correct?

**Comment by kevaldoshi17** [comment]
@lebrice Not quite, due to the dependency issue, ./update.sh doesn't install all the packages. For my temporary fix, I manually installed wandb and then commented the last line in ./update.sh. Also for some reason, in the dockerfile it requires `RUN pip install -I git+https://www.github.com/lebrice/Sequoia.git@cvpr_competition_dev#egg=sequoia[monsterkong]` instead of --upgrade. Same for ./update.sh, it needs `pip install -I -r requirements.txt`.
