### ISSUE TITLE
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.

### ISSUE THREAD

**Issue by francesco-p** [fgolemo/cl-workshop-cvpr21-docker#2]
After running `./install <token>` I get:

`CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.`

yes I've `conda init bash/zsh/whatever`
yes I restarted the shell
yes everything works outside the script

It seems a common problem as can be seen here https://github.com/conda/conda/issues/7980 
tldr; running conda activate inside a script _sometimes_ breaks everything, maintainers don't want to fix it 

A workaround is injecting `eval "$(conda shell.bash hook)"` before `conda activate clcomp21` .

Is a pr needed?
Thanks, cya
 
--- 

`uname -a`
`Linux  5.8.0-44-generic #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

`conda --version`
`conda 4.9.2`

**Comment by lebrice** [comment]
Hello @francesco-p , thanks for posting! I'll test this out on my end, but feel free to make a PR!

**Comment by lebrice** [comment]
By the way, did you try `source install.sh <your token>` ?

**Comment by lebrice** [comment]
I believe this should be fixed by #3, but I'll double-check tomorrow. Thanks for posting!

**Comment by fgolemo** [comment]
@francesco-p thanks for pointing this out. Your fix seems to have worked and was merged into main. Could you try again please, after pulling the latest commit?

**Comment by francesco-p** [comment]
> @francesco-p thanks for pointing this out. Your fix seems to have worked and was merged into main. Could you try again please, after pulling the latest commit?

Yesterday I've cloned your repo and set up another machine and it worked so I guess it's ok now :) :100:
