### ISSUE TITLE
Add HAT Example

### ISSUE THREAD

**Issue by lebrice** [fgolemo/cl-workshop-cvpr21-docker#7]
Should an example of something like "Hard Attention to Task", probably by porting and adapting the [HAT example from Sequoia](https://github.com/lebrice/Sequoia/blob/master/examples/advanced/hat_demo.py) and using the task inference from `multihead_classifier.py`.

**Comment by lebrice** [comment]
On second thought, maybe it should be the other way around, and we should just update the existing example in Sequoia to work on the SL track of the competition, and then redirect users there? What do you think @fgolemo?

**Comment by fgolemo** [comment]
What's that supposed to be for?
